sudo: false
language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  include:
    - go: 1.5
      addons:
         mariadb: 5.5
    - go: 1.5
      addons:
         mariadb: "10.0"
    - go: 1.5
      addons:
         mariadb: 10.1

before_script:
  - mysql -e "create database /*M!50701 IF NOT EXISTS */ gotest;"
